[package]
name = "net"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
core = { path = "../core" }
dashmap = "7.0.0-rc2"
futures = "0.3.31"