[package]
name = "score"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }

serde_json = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = { workspace = true }