[package]
name = "score"
version = "0.1.0"
edition = "2024"

[dependencies]

serde = { version = "1.0.219", features = ["derive"] }

serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }